version: "3"

services:
  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_BASE_URL=http://api
    entrypoint: npm run dev
  api:
    image: clue/json-server
    ports:
      - "3333:80"
    volumes:
      - ./server.json:/data/db.json
  redis:
    image: redis:alpine
    command: redis-server
