version: "3"

services:
  graphql-server:
    build: .
    container_name: graphql-server
    ports:
      - "4000:4000"
    depends_on:
      - graphql-redis
      - graphql-api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_BASE_URL=http://api
    networks:
      - grahpql-network
    entrypoint: npm run dev
  graphql-api:
    container_name: graphql-api
    image: clue/json-server
    ports:
      - "3333:80"
    volumes:
      - ./server.json:/data/db.json
    networks:
      - grahpql-network
  graphql-redis:
    container_name: graphql-redis
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - grahpql-network

networks:
  grahpql-network:
    driver: bridge
